-- HR System - Sequence Definitions
-- Auto-increment sequences for primary keys

CREATE SEQUENCE SEQ_EMPLOYEE_ID
    START WITH 1000
    INCREMENT BY 1
    NO CACHE;

CREATE SEQUENCE SEQ_DEPARTMENT_ID
    START WITH 100
    INCREMENT BY 1
    NO CACHE;

CREATE SEQUENCE SEQ_SALARY_HISTORY_ID
    START WITH 1
    INCREMENT BY 1
    NO CACHE;

CREATE SEQUENCE SEQ_AUDIT_LOG_ID
    START WITH 1
    INCREMENT BY 1
    NO CACHE;

CREATE SEQUENCE SEQ_SESSION_ID
    START WITH 1
    INCREMENT BY 1
    NO CACHE;

CREATE SEQUENCE SEQ_RATING_ID
    START WITH 1
    INCREMENT BY 1
    NO CACHE;

CREATE SEQUENCE SEQ_BONUS_ID
    START WITH 1
    INCREMENT BY 1
    NO CACHE;

CREATE SEQUENCE SEQ_CREDENTIAL_ID
    START WITH 1
    INCREMENT BY 1
    NO CACHE;

COMMIT;
